name: on_pull_request_owner
on: pull_request
jobs:
  build:
    if: github.event.pull_request.user.login == 'brihter'
    env:
      NODE_ENV: test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node: [ '16.x', '18.x', '20.x', '22.x' ]
        provider: [ 'aws', 'cloudflare' ]
    name: build
    steps:
      - name: environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: checkout
        uses: actions/checkout@v2
      - name: install
        run: ./bin/install.sh
      - name: test, type=local
        run: npm run test -- --type=local --provider=local
      - name: test, type=s3
        run: npm run test -- --type=s3 --provider=${{ matrix.provider }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ACCESS_KEY_ID: ${{ secrets.CF_ACCESS_KEY_ID }}
          CF_SECRET_ACCESS_KEY: ${{ secrets.CF_SECRET_ACCESS_KEY }}
