name: on_push_main
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    env:
      NODE_ENV: test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [ '18.x' ]
    name: build
    steps:
      - name: environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: checkout
        uses: actions/checkout@v2
      - name: install
        run: ./bin/install.sh
      - name: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
          access: public
