name: brighter/storage
on: [push]
jobs:
  build:
    env:
      NODE_ENV: test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [ '16.x', '18.x' ]
    name: build
    steps:
      - name: environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: "credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-central-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: checkout
        uses: actions/checkout@v2
      - name: install
        run: ./bin/install.sh
      - name: test
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ACCESS_KEY_ID: ${{ secrets.CF_ACCESS_KEY_ID }}
          CF_SECRET_ACCESS_KEY: ${{ secrets.CF_SECRET_ACCESS_KEY }}
        run: ./bin/test.sh
